### ISSUE TITLE
How to add new sound with button ?

### ISSUE THREAD

**Issue by NBSDEVApp** [xtonousou/xSoundBoardHD#19]
Hi,
I have search where is the .mp3 button with name of this but didn't find.
I need to add button and change the sound.
Thanks

**Comment by xtonousou** [comment]
Could you be more specific?

**Comment by NBSDEVApp** [comment]
Sorry i have found what i search.
But i have other question, where is the categories icon : the asterix, smile, gamepad, ... 
I have not found this i search it for change it
Thanks

**Comment by xtonousou** [comment]
Refer to [here](https://github.com/xtonousou/SoundBoardX/blob/master/app/src/main/java/io/github/xtonousou/soundboardx/MainActivity.java#L358). See `.withIcon()` method calls.

**Comment by NBSDEVApp** [comment]
Thanks and what version of awesome icon is used ?

**Comment by xtonousou** [comment]
Inside `app/build.gradle` you see this line `implementation 'com.mikepenz:fontawesome-typeface:4.7.0.2@aar'`. Refer to the [upstream](https://github.com/mikepenz/Android-Iconics/blob/master/README.md) to check the latest version. It is updated frequently, so make sure to replace the version inside `app/build.gradle`. Right now, as you can see, `SoundBoardX` uses `FontAwesome 4.7`.
